### ISSUE TITLE
prototype_mwcog's mandatory_tour_scheduling.compute_logsums creates negative durations, causing negative parking costs

### ISSUE THREAD

**Issue by i-am-sijia** [ActivitySim/activitysim#698] opened 2023-09-12 23:12 UTC
**Describe the bug**
In prototype_mwcog's mandatory tour scheduling model, the calculate_logsums step creates negative tour durations, which creates negative parking costs that are used in the logsum calculation, see screenshot below.

The cause of this issue is in the definition of time periods, and how ActivitySim uses it to create `in_period` and `out_period` combinations to calculate logsum for mandatory tour scheduling.  The code creates `in_period` and `out_period` combinations based on the sequence in the skim_time_period["labels"]
https://github.com/ActivitySim/activitysim/blob/180dcca9e63f650753d63d65c06f58a9dbe6e4ba/activitysim/examples/prototype_mwcog/configs/network_los.yaml#L34-L39
and then uses [tour_departure_and_duration_segments.csv](https://github.com/ActivitySim/activitysim/blob/develop/activitysim/examples/prototype_mwcog/configs/tour_departure_and_duration_segments.csv) to look up the `start` and `end` time based on the `in_period` and `out_period` combinations. `duration` is then *naively* calculated in the ActivitySim source code using end - start, which can cause negative values.

In the prototype_mwcog specification, the following time period combination will be created for logsum calculation:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wangs1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wangs1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tour_id | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154 | 6519154
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
out_period | NT | NT | NT | NT | AM | AM | AM | AM | MD | MD | MD | PM | PM
in_period | NT | AM | MD | PM | AM | MD | PM | NT | MD | PM | NT | PM | NT
start | 33 | 33 | 33 | 33 | 9 | 9 | 9 | 9 | 13 | 13 | 13 | 25 | 25
end | 33 | 10 | 24 | 27 | 10 | 24 | 27 | 33 | 24 | 27 | 33 | 27 | 33
duration | 0 | -23 | -9 | -6 | 1 | 15 | 18 | 24 | 11 | 14 | 20 | 2 | 8

</body>

</html>

**To Reproduce**
1. Run test_mwcog() in [test_mwcog.py](https://github.com/ActivitySim/activitysim/blob/180dcca9e63f650753d63d65c06f58a9dbe6e4ba/activitysim/examples/prototype_mwcog/test/test_mwcog.py#L67)
2. Set `trace_hh_id` to 1590
3. Open "...\output\trace\mandatory_tour_scheduling\vectorize_tour_scheduling\tour_1\school\compute_logsums\logsums\tour_mode_choice_annotate_choosers_preprocessor-4f9b90.csv"
4. You will see for some columns the duration is negative and the resulting parking cost is negative. You can see the negative parking cost is used in subsequent utility calculations.

**Expected behavior**
There should not be negative tour duration nor negative parking cost.

**Screenshots**
![image](https://github.com/ActivitySim/activitysim/assets/28812722/7e15a75b-d43f-4be2-96cb-6d8d452b3bb6)

**Additional context**
There are actually rules on the time period definition, but not sure if it is documented. Might lead to a future code improvement to deal with time periods span over midnight.

**Relevant issues**
https://github.com/ActivitySim/activitysim/issues/697

**Comment by AndrewTheTM** [comment] 2023-09-13 15:57
MWCOG's prototype is behind the production model. We fixed this in production by looking for those negative durations and fixing them in tour_mode_choice_annotate_chooers_preprocessor.csv:

`,start,"np.where((df.duration < 0) & (df.out_period == 'NT'), 5, df.start) if 'start' in df.columns else np.nan"
,duration,(df.end - start) if 'start' in df.columns else df.duration`

ETA: the duration will still show as negative, but the parking cost will show positive.

**Comment by jfdman** [comment] 2023-09-28 16:57
@i-am-sijia  I am closing this as it is not a bug in the production model.

**Closed as completed by jfdman** 2023-09-28 16:57 UTC
Labels: Bug
