### ISSUE TITLE
'Work' trips vs. 'work' trips

### ISSUE THREAD

**Issue by esanchez01** [ActivitySim/activitysim#442] opened 2021-06-22 19:11 UTC
While summarizing the SANDAG 3 Zone example outputs, we noticed that both a `work` and `Work` trip purpose existed. After investigating, it appears that `Work` trips are strictly inbound at-work sub-tour trips with a workplace destination -- this is enforced in [trip_purpose.py](https://github.com/ActivitySim/activitysim/blob/a57efa1418320cb88d72ad5f413aaa45131183a4/activitysim/abm/models/trip_purpose.py#L161).

With that said, should the purpose instead be `work` so that it is consistent with other work trips? If it was intentionally named `Work` to differentiate these trips from non-at-work sub-tour trips, would it make sense to rename this purpose to a name that makes its difference to 'normal' work trips more explicit? Otherwise, `Work` trips could be interpreted as additional `work` trips or possibly duplicates.

**Comment by wusun2** [comment] 2021-06-22 19:41
@esanchez01 , what is the outbound purpose of this at-work tour example?

**Comment by esanchez01** [comment] 2021-06-22 20:54
> @esanchez01 , what is the outbound purpose of this at-work tour example?

The overall sub-tour purpose is `atwork`. The first outbound trip purpose appears to always be `atwork`. The final inbound trip purpose is then `Work` as described above.

**Comment by wusun2** [comment] 2021-06-22 21:41
@bstabler, on an at-work tour, should the first outbound trip purpose set to a 'real' purpose such as eat out, recreational, etc instead of at-work?

**Comment by bstabler** [comment] 2021-06-22 23:09
I think this might be issue #392, which I think is just a holdover from CT-RAMP.  The line of interest is [here](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/models/trip_purpose.py#L164).   @esanchez01 - I think you mean trip_purpose.py instead of simulate.py above?

**Comment by esanchez01** [comment] 2021-06-23 01:35
> I think this might be issue #392, which I think is just a holdover from CT-RAMP. The line of interest is [here](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/models/trip_purpose.py#L164). @esanchez01 - I think you mean trip_purpose.py instead of simulate.py above?

Yes, trip_purpose.py. This does seem to be the same issue you referenced. Thanks!

**Comment by bstabler** [comment] 2021-06-24 18:18
I'll spend a little time looking into this some more with the plan of tidying this up:
  - the capitalization issue
  - the "real" purpose
  - make it less confusing, more intuitive
  - fix example expressions, notebooks

**Comment by bstabler** [comment] 2021-06-28 23:40
The commit above removes the capitalization.  The rules for assigning purpose are below, along with a screenshot with consistent results:
  - last trip of outbound tour gets tour primary_purpose
  - last trip of inbound tour gets home (or work for atwork subtours)
  - intermediate stops (non-last trips) purpose assigned by probability table _trip_purpose_probs.csv_, which includes a "work" purpose as well

![image](https://user-images.githubusercontent.com/5761221/123713656-bbbe4600-d829-11eb-94bc-500cd1a0ea77.png)

I expect the agency examples regress tests to not pass since the expected trips table includes the capitalization.  After running all the tests, I will update the expected trips table with the new one and then re-run the tests so all the tests pass.

**Comment by esanchez01** [comment] 2021-06-30 00:00
@bstabler, I reviewed and discussed this over with @wusun2. We had a couple comments:

- The order for some intermediate trips are strange, as shown in tour_id 13286136 and 66923525 of the screenshot you shared. For the latter tour, the first outbound trip's purpose is 'work' yet it originates from the workplace. It is understood that these intermediate trips are assigned a purpose probabilistically but we wouldn't expect such cases to happen. More generally, maybe the logic for assigning purposes to at-work subtour trips should be rethought?
- It would be better to call the last inbound trip for at-work subtours something other than 'work' -- this would distinguish it from regular work trips for reporting purposes.

**Comment by bstabler** [comment] 2021-07-09 22:40
@joecastiglione noticed that some coefficients are both in the coefficient file and still hardwired into the expressions file.  I think these just got forgotten in the migration from expression files to expression files + coefficient files for estimation integration.  I just updated these.

**Comment by bstabler** [comment] 2021-07-09 22:46
We agreed on the 7/8 call to set aside the issues @esanchez01 notes since they're lower priority than other current issues.

**Comment by bstabler** [comment] 2021-10-07 17:54
I need to update the regression test files for the example and then we can close this issue

**Closed as completed** 2021-11-05 17:53 UTC
